[lesson-3] task-1
Ibadichan/ruby-course1 pull request #1
Opened 2017-03-14 23:33 UTC by Ibadichan

2017-03-15 14:07 UTC, webmstk requested changes

2017-03-15 14:07 UTC, webmstk commented on lesson-3/task-1.rb
> +  def all_stations
Этот метод дёргается довольно часто, и каждый раз массив вычисляется. Лучше изначально хранить массив со станциями, обновляя его по мере необходимости. Или кешировать, используя инстанс переменную )

2017-03-15 14:07 UTC, webmstk commented on lesson-3/task-1.rb
> +  def all_stations
Да и назвать можно просто stations. Если не уточнять, подразумевается, что все станции

2017-03-15 14:07 UTC, webmstk commented on lesson-3/task-1.rb
> +  attr_reader :type, :number ,:cars, :route
запятая убежала :)

2017-03-15 16:44 UTC, iBublik requested changes

2017-03-15 16:44 UTC, iBublik commented on lesson-3/task-1.rb
> +    @start_station = start_station
Лучше упростить - храни все станции в одном массиве. Первая будет начальной, а последняя - конечной (менять эти станции нельзя)

2017-03-15 16:44 UTC, iBublik commented on lesson-3/task-1.rb
> +    return if @cars == 0  # нельзя уменьшить вагоны когда их 0
Раз тут уже есть return, заодно воткни сюда проверку скорости (ее, кстати, можно вынести в отдельный метод с говорящим названием для лучшего понимания происходящего).

2017-03-15 16:44 UTC, iBublik commented on lesson-3/task-1.rb
> +    @step += 1
Таким образом можно выйти за рамки маршрута.

2017-03-15 16:44 UTC, iBublik commented on lesson-3/task-1.rb
> +    @step -= 1
Тут значение может стать отрицательным

2017-03-15 16:44 UTC, iBublik commented on lesson-3/task-1.rb
> +    @route.all_stations[@step-1]
А если мы на начальной станции находимся?

2017-03-15 16:44 UTC, iBublik commented on lesson-3/task-1.rb
> +    @route.all_stations[@step+1]
А если мы на конечной станции находимся?

2017-03-16 09:41 UTC, iBublik requested changes

2017-03-16 09:41 UTC, iBublik commented on lesson-3/task-1.rb
> +  def by_type(type)
`station.by_type('passenger')` - из названия непонятно, что мы поезда выбираем

2017-03-16 09:41 UTC, iBublik commented on lesson-3/task-1.rb
> +    @stations.delete(station)
Нельзя позволять убрать начальную или конечную станции

2017-03-16 09:41 UTC, iBublik commented on lesson-3/task-1.rb
> +    return if @cars == 0  && stopped
Зачем тут проверка, что поезд стоит?

2017-03-16 09:41 UTC, iBublik commented on lesson-3/task-1.rb
> +  def positive_step
Смысл выноса таких кусочков в отдельные методы - это упрощение понимания предметной области. В случае с `stopped` мы уточнили, что проверяем скорость поезда чтоб понять стоит ли он на месте. А этот метод своим именем скорее запутывает. Почему `step` должен быть положительным числом? 
Кстати, методы возвращающие логический результат (предикаты) принято называть со знаком вопроса на конец

2017-03-16 13:46 UTC, vkurennov approved these changes
Принято, но поправь замечания

2017-03-16 13:46 UTC, vkurennov commented on lesson-3/task-1.rb
> +    @step += 1 if can_next?
Я бы назвал это не step, а index, там же индекс станции хранится

2017-03-16 13:46 UTC, vkurennov commented on lesson-3/task-1.rb
> +  def next_step
Лучше назвать методы по сути их задачи. В данном случае - движение вперед, вот и назови `forward`

2017-03-16 13:46 UTC, vkurennov commented on lesson-3/task-1.rb
> +  def prev_step
А этот `backward` назови

2017-03-16 20:36 UTC, merged