lesson-9
Ibadichan/ruby-course1 pull request #9
Opened 2017-04-03 21:54 UTC by Ibadichan

2017-04-04 11:33 UTC, iBublik requested changes

2017-04-04 11:33 UTC, iBublik commented on lesson-9/acessors.rb
> +    define_method('history'.to_sym) do |var_name, value|
В принципе, все эти действия можно было сделать внутри сеттера. Но если уж выносить в отдельный метод, то есть замечания:
1. Методы-команды лучше именовать глаголами. Например, `store_in_history`
2. Этот метод пересоздается при каждом вызове attr_accessor_with_history, это избыточно
3. Создавать этот метод динамически вообще нет нужды, можно просто объявить его как обычный метод

2017-04-04 11:33 UTC, iBublik commented on lesson-9/acessors.rb
> +      raise 'invalid class!!!' if value.class != type
Для проверки классов лучше использовать метод `is_a?`

2017-04-04 11:33 UTC, iBublik commented on lesson-9/car.rb
> +require_relative'manufacturer'
Пробел потерялся

2017-04-04 11:33 UTC, iBublik commented on lesson-9/cargo_car.rb
> +require_relative('car')
Подключение файлов принято писать без скобок, чтоб выглядело как команда:
`require_relative 'car'`

2017-04-04 11:33 UTC, iBublik commented on lesson-9/validation.rb
> +      true
Лучше `true` вернуть после вызова `validate!` в методе `valid?`, а отсда просто убрать. Этот метод является командой - его задача выполнить набор действий, выбросить исключение, а не вернуть результат

2017-04-04 11:33 UTC, iBublik commented on lesson-9/validation.rb
> +        if type_validation == :presence && (attr.nil? || attr.empty?)
Представь, что мы добавим еще один тип валидации. Тогда этот метод разрастется, хотя и сейчас он уже немаленький. Мы можем создать скрытых приватных методов, выполняющих определенную валидацию, и вызывать их через `send`.

2017-04-04 11:33 UTC, iBublik commented on lesson-9/validation.rb
> +        elsif type_validation == :type && (attr.all? { |item| item.class != parameter } || (attr.class != parameter && attr.class != Array)) # Sorry !!!
Этот код упадет, если `attr` не умеет отзываться на `all?`. В задаче нам требуется проверять класс объекта, даже если он является массивом, то надо проверять не его элементы, а сам объект.

2017-04-05 04:17 UTC, vkurennov requested changes

2017-04-05 04:17 UTC, vkurennov commented on lesson-9/validation.rb
> +        send(type_validation, attr, parameter)
У тебя в type_validation будут значения типа :presence, :format и :type, соответственно, и методы с такими же именами будут вызываться, а таких методов у тебя нет, они называются по-другому.

2017-04-05 08:56 UTC, iBublik approved these changes

2017-04-05 23:50 UTC, vkurennov approved these changes

2017-04-06 11:06 UTC, merged